const CadastroCompraLocators = {
  formPrincipal: '#form-compra, form[action*="compra"], form[id*="compra"]',
  btnTopoVoltar: 'a[href*="/compra"]',
  btnTopoNovo: 'a[href*="/compra/novo"]',
  btnTopoSalvar: '#btn-salvar',
  btnTopoExcluir: '.title_nota_fiscal_de_compra .btn-danger:contains("Excluir"), #btn-excluir',
  btnMaisAcoes: '#btn-mais-acoes',
  campoFornecedor: '#auto_cliente_fornecedor_id',
  hiddenFornecedorId: '#fornecedor_id',
  btnFornecedorAutocomplete: '#auto_icon_cliente_fornecedor_id',
  campoObservacoes: '#observacao',
  listaFornecedorSugestoes: '#div_auto_cliente_fornecedor_id .typeahead-list li',
  // Campos principais da nota
  campoNatureza: '#auto_cfop_id',
  btnNaturezaAutocomplete: '#auto_icon_cfop_id',
  listaNaturezaSugestoes: '#div_auto_cfop_id .typeahead-list li',
  campoNumero: '#numero_nfe',
  campoSerie: '#serie',
  campoChaveAcesso: '#chave_acesso',
  // Modal de novo item
  btnNovoItem: 'button:contains("Novo Item"), .btn-novo-item',
  modalNovoItem: '.modal.in, .modal.show',
  modalTituloNovoItem: '.modal h2:contains("Novo Item")',
  modalCampoProduto: '.modal #auto_produto_id',
  modalBtnProdutoAutocomplete: '.modal #auto_icon_produto_id',
  modalListaProdutoSugestoes: '.modal #div_auto_produto_id .typeahead-list li',
  modalCampoPreco: '.modal #valor_unitario_comercial',
  modalCampoQuantidade: '.modal #quantidade_comercial',
  modalCampoNaturezaItem: '.modal #auto_cfop_item_id',
  modalBtnNaturezaItemAutocomplete: '.modal #auto_icon_cfop_item_id',
  modalListaNaturezaItemSugestoes: '.modal #div_auto_cfop_item_id .typeahead-list li',
  modalBtnAdicionarItem: '.modal #btn-adicionar',
  listaProdutoSugestoes: '#div_auto_produto_empresa_grade_id_ .typeahead-list li',
  campoProduto: '#auto_produto_empresa_grade_id_',
  btnProdutoAutocomplete: '#auto_icon_produto_empresa_grade_id_',
  campoDescricaoItem: '#descricao_item_',
  campoQuantidadeItem: '#quantidade_',
  campoPrecoItem: '#preco_',
  tabelaItens: 'table.tabela-itens, .panel_content_adicione_os_itens_na_compra table.table-form, .panel_content_adicione_os_itens table.table-form',
  itensSalvos: 'table.tabela-itens tbody tr[data-id], .panel_content_adicione_os_itens_na_compra table.table-form tbody tr[data-id], .panel_content_adicione_os_itens table.table-form tbody tr[data-id]',
  totalizadorQuantidade: '.col-totais .quantidade span',
  totalizadorTotal: '.col-totais .total span',
  painelPagamentosTabela: 'table.tabela-pagamento, .table-pagamentos',
  painelPagamentosMensagem: 'table.tabela-pagamento tbody tr td, .table-pagamentos tbody tr td',
  linhasPagamentos: 'table.tabela-pagamento tbody tr, .table-pagamentos tbody tr',
  btnGerarPagamento: ':nth-child(5) > .ibox > .ibox-title .btn:contains("Gerar Pagamento")',
  modalFormaPagamentoIcon: '.modal #auto_icon_forma_pagamento_id',
  modalSugestoesFormaPagamento: '.modal #div_auto_forma_pagamento_id .typeahead-list li',
  modalBtnSalvarPagamento: '.modal #btn-salvar',
  modalCampoFormaPagamento: '.modal #auto_forma_pagamento_id',
  modalVisivel: '.modal.in, .modal.show',
  btnAplicarDesconto: '#btn-desconto',
  formAplicarDesconto: '#form-aplicar-descontos',
  inputDescontoPercentual: '#totais_percentual',
  selectTipoDesconto: '#tipo',
  btnConfirmarDesconto: '#btn_aplicar',
};

export default CadastroCompraLocators;

