const CadastroVendaLocators = {
  formPrincipal: '#form-venda',
  btnTopoVoltar: '.ibox-title #btn-voltar',
  btnTopoNovo: '.ibox-title #btn-novo',
  btnTopoSalvar: '#btn-salvar',
  btnTopoExcluir: '#btn-excluir',
  btnMaisAcoes: '#btn-mais-acoes',
  campoCliente: '#auto_cliente_id',
  hiddenClienteId: '#cliente_id',
  btnClienteAutocomplete: '#auto_icon_cliente_id',
  campoVendedor: '#auto_funcionario_id',
  hiddenVendedorId: '#funcionario_id',
  btnVendedorAutocomplete: '#auto_icon_funcionario_id',
  campoObservacoes: '#observacao',
  campoIndicador: '#auto_indicador_id',
  listaClienteSugestoes: '#div_auto_cliente_id .typeahead-list li',
  listaVendedorSugestoes: '#div_auto_funcionario_id .typeahead-list li',
  listaProdutoSugestoes: '#div_auto_produto_empresa_grade_id_ .typeahead-list li',
  campoProduto: '#auto_produto_empresa_grade_id_',
  btnProdutoAutocomplete: '#auto_icon_produto_empresa_grade_id_',
  campoDescricaoItem: '#descricao_item_',
  campoQuantidadeItem: '#quantidade_',
  campoPrecoItem: '#preco_',
  tabelaItens: '.panel_content_adicione_os_itens_na_venda table.table-form',
  itensSalvos: '.panel_content_adicione_os_itens_na_venda table.table-form tbody tr[data-id]',
  totalizadorQuantidade: '.col-totais .quantidade span',
  totalizadorTotal: '.col-totais .total span',
  painelPagamentosTabela: '.table-pagamentos',
  painelPagamentosMensagem: '.table-pagamentos tbody tr td',
  linhasPagamentos: '.table-pagamentos tbody tr',
  btnGerarPagamento: '#btn-gerar-pagamento',
  modalFormaPagamentoIcon: '#auto_icon_forma_pagamento_id',
  modalSugestoesFormaPagamento: '.modal .typeahead-list li',
  modalBtnSalvarPagamento: '.modal #btn-salvar',
  modalCampoFormaPagamento: '#auto_forma_pagamento_id',
  modalVisivel: '.modal.in, .modal.show',
  btnAplicarDesconto: '#btn-desconto',
  formAplicarDesconto: '#form-aplicar-descontos',
  inputDescontoPercentual: '#totais_percentual',
  selectTipoDesconto: '#tipo',
  btnConfirmarDesconto: '#btn_aplicar',
  btnConfirmarDescontoAcao: '#btn_aplicar_desconto',
  alertaDesconto: '#text_descontos',
  totalDescontosCampo: '#totais_desconto, input[name="totais_desconto"], input[name="totais[desconto]"]',
  sweetAlertModal: '.sweet-alert',
  sweetAlertConfirmBtn: '.sweet-alert .confirm',
};

export default CadastroVendaLocators;
