const CadastroNfeLocators = {
  tituloPagina: '.ibox-title h5',
  botaoVoltarListagem: '.ibox-title .btn-default',
  botaoMaisAcoes: '#more-options, button:contains("Mais ações"), button.dropdown-toggle:contains("Mais ações")',
  botaoNovoCadastroheader: '.ibox-title a.btn.btn-warning[href*="/nfe2/novo"]',
  botaoExcluir: '#destroy-nfe-btn',
  widgetStatus: '#nfe-status-widget',
  badgeStatus: '#status_da_nota_cancelada, button:contains("Autorizada"), button:contains("Cancelada"), button:contains("Em Elaboração"), button:contains("Aguardando"), #nfe-status-widget button',
  stepsHeader: '.dto-step-header-item',
  stepFinalidadeAtivo: '.dto-step-header-item[data-step="0"].active',
  tabsTipoNota: {
    normal: '#tab-normal',
    devolucao: '#tab-devolucao',
    ajuste: '#tab-ajuste',
    complementar: '#tab-complementar',
  },
  conteudoTabs: {
    normal: '#tab-content-normal',
    devolucao: '#tab-content-devolucao',
    ajuste: '#tab-content-ajuste',
    complementar: '#tab-content-complementar',
  },
  formulario: '#nfe-form',
  formularioPadrao: '#nfe-form-padrao',
  camposPrincipais: {
    finalidade: '#finalidade',
    naturezaAuto: '#auto_natureza',
    naturezaCodigo: '#codigo_natureza',
    dataHoraEmissao: '#data_hora_emissao',
    dataHoraSaida: '#data_hora_saida',
    serie: '#serie',
    indicadorPresencial: '#indicador_presencial',
    movimentarEstoqueSwitch: '#switcher_movimentar_estoque',
  },
  destinatario: {
    painel: '#painel-destinatario',
    nome: '#auto_destinatario_nome',
    nomeHidden: '#destinatario_nome',
    cpfCnpj: '#destinatario_cpf_cnpj',
  },
  notasReferenciadas: {
    painel: '#notas-referenciadas, [id*="notas-referenciadas"], .notas-referenciadas',
    painelAccordion: '#panel_referenced_nfe',
    botaoExpandirAccordion: '#panel_referenced_nfe > .col-sm-12 > .ibox > .ibox-title > .row > .m-b-xs > .col-lg-1 > .ibox-tools > .collapse-link > .fa',
    botaoAdicionar: '#btn-adicionar-nota-referenciada, button:contains("Adicionar"), [id*="adicionar-nota"]',
    campoChaveAcesso: '#auto_referenced_chave_acesso',
    campoChaveAcessoIcone: '#auto_icon_referenced_chave_acesso',
    campoChaveAcessoContainer: '#div_auto_chave_acesso_referenciada, [id*="div_auto_chave_acesso_referenciada"]',
    tabelaNotas: '#table-notas-referenciadas, table tbody[id*="notas-referenciadas"]',
    linhasTabela: '#table-notas-referenciadas tbody tr, table tbody[id*="notas-referenciadas"] tr',
    botaoSalvar: '#form-notas-referenciadas >> .btn-primary:contains("Salvar")',
  },
  typeaheadPrimeiroItem: '.typeahead-list li a',
  radiosTipoNfe: {
    venda: '#radio_toggle_tipo_nfe_VENDA',
    nfce: '#radio_toggle_tipo_nfe_NFCE',
    movimentacao: '#radio_toggle_tipo_nfe_MOVIMENTACAO',
    avulsa: '#radio_toggle_tipo_nfe_AVULSA',
  },
  radiosTipoDevolucao: {
    compra: '#radio_toggle_tipo_nfe_COMPRA',
    movimentacao: '#radio_toggle_tipo_nfe_MOVIMENTACAO',
    notaFiscalSaida: '#radio_toggle_tipo_nfe_NOTAFISCAL',
    trocas: '#radio_toggle_tipo_nfe_TROCA',
    avulsa: '#radio_toggle_tipo_nfe_AVULSA',
  },
  skeletonForm: '#nfe-form-skeleton',
  skeletonItems: '#nfe-items-skeleton',
  skeletonPayments: '#nfe-payments-skeleton',
  painelEmitirNota: '#content-finish-step',
  /** Resumo da etapa final (totais na emissão); mesmo container que painelEmitirNota */
  resumoEmissao: {
    painel: '#content-finish-step',
  },
  emitirNotaBotao: '#issue-invoice',
  emitirNotaIcone: '#issue-invoice-icon',
  modalSucessoEmissao: {
    container: '.sweet-alert.showSweetAlert.visible',
    titulo: '.sweet-alert h2',
    descricao: '.sweet-alert p',
    botaoListagem: '.sweet-alert .cancel',
    botaoNovaNota: '.sweet-alert .confirm',
  },
  cancelamento: {
    botaoCancelar: '#cancel-nfe-btn, button:contains("Cancelar"), a:contains("Cancelar")',
    dropdownAcoes: '#more-options, button.dropdown-toggle',
    opcaoCancelar: '.dropdown-menu a:contains("Cancelar NFe"), .dropdown-menu a:contains("Cancelar"), .dropdown-menu button:contains("Cancelar")',
    // SweetAlert de confirmação inicial: "Deseja cancelar esta Nota?"
    sweetAlertConfirmacao: {
      container: '.sweet-alert.showSweetAlert.visible',
      titulo: '.sweet-alert h2',
      botaoConfirmar: '.sweet-alert .confirm:contains("Sim, pode continuar!"), button:contains("Sim, pode continuar!")',
      botaoCancelar: '.sweet-alert .cancel:contains("Não, desejo voltar!"), button:contains("Não, desejo voltar!")',
    },
    // Modal nativo de cancelamento: "Cancelamento da Nota" com campo de justificativa
    modalCancelamento: {
      container: '[role="dialog"], .modal.show, .modal.in, dialog',
      titulo: 'h2:contains("Cancelamento da Nota"), .modal-title:contains("Cancelamento")',
      campoMotivo: '[role="dialog"] input[type="text"], [role="dialog"] textarea, .modal input[type="text"], .modal textarea, input[placeholder*="motivo"], input[placeholder*="justificativa"]',
      botaoConfirmar: '.modal #btn-save:contains("Cancelar")',
      botaoVoltar: '[role="dialog"] button:contains("Voltar"), .modal button:contains("Voltar")',
    },
    // Alerta de sucesso após cancelamento
    alertaSucesso: {
      container: '.alert-success, .alert, [role="alert"]',
      titulo: '.alert-success strong, .alert strong, [role="alert"] strong',
      mensagem: '.alert-success, .alert',
    },
  },
  maisAcoes: {
    dropdown: '#more-options, button.dropdown-toggle',
    opcoes: {
      cancelar: 'a:contains("Cancelar NFe"), a[href*="cancelar"]',
      downloadXml: 'a:contains("Download XML"), a[href*="baixar-xml"], a[href*="download-xml"]',
      visualizarDanfe: 'a:contains("Visualizar Danfe"), a[href*="visualizar-danfe"], a[href*="danfe"]',
      cartaCorrecao: '#correction-letter, a[href*="carta-correcao"], a[id*="correction"]',
      enviarEmail: 'a:contains("Enviar email"), a[href*="enviar-email"], button:contains("Enviar email")',
      clonar: 'a:contains("Clonar NFe"), a[href*="clonar"], a[id*="clonar"]',
    },
  },
  cartaCorrecao: {
    botaoCartaCorrecao: '#carta-correcao-nfe-btn, #correction-letter',
    dropdownAcoes: '#more-options, button.dropdown-toggle',
    opcaoCartaCorrecao: '#correction-letter, a[href*="carta-correcao"], a[id*="correction"]',
    // Modal de carta de correção: "Carta de Correção Eletrônica" com campo de correção
    modalCartaCorrecao: {
      container: '[role="dialog"], .modal.show, .modal.in, dialog, #content-plus.modal',
      titulo: 'h2, .modal-title, heading[level="2"]',
      campoCorrecao: '[role="dialog"] textarea, .modal textarea, textarea[placeholder*="correção"], textarea[placeholder*="corrigir"], textarea[name*="correcao"], [role="dialog"] input[type="text"], .modal input[type="text"], input[placeholder*="Mensagem"], textbox[aria-label*="Mensagem"], #content-plus textarea, #content-plus input[type="text"], #content-plus input[type="text"][name*="mensagem"], #content-plus input[type="text"][name*="correcao"]',
      botaoConfirmar: '[role="dialog"] button, .modal button, #content-plus button',
      botaoVoltar: '[role="dialog"] button, .modal button, #content-plus button',
    },
    // Alerta de sucesso após emissão da carta de correção
    alertaSucesso: {
      container: '.alert-success, .alert, [role="alert"]',
      titulo: '.alert-success strong, .alert strong, [role="alert"] strong',
      mensagem: '.alert-success, .alert',
    },
    // Badge ou indicador de carta de correção emitida
    badgeCartaCorrecao: '#status_carta_correcao, button:contains("CCe"), [data-carta-correcao]',
  },
  tour: {
    container: '.shepherd-content',
    naoMostrarNovamente: '.shepherd-button-do-not-show',
  },
  itens: {
    painel: '#nfe-items-content, #div-itens-form, #div-itens-from, #painel-itens, .panel_content_adicione_os_itens',
    tabelaContainer: '#nfe-items-table, #nfe-items, #nfe-items-content .table-responsive',
    produtoAutocomplete: '#auto_produto_empresa_grade_id_, #auto_produto_empresa_grade_id, #auto_nome_, input[id^="auto_nome"]',
    produtoIcon: '#auto_icon_produto_empresa_grade_id_, #auto_icon_produto_empresa_grade_id, #auto_icon_nome_, [id^="auto_icon_nome"]',
    produtoHiddenId: '#produto_empresa_grade_id_, #produto_empresa_grade_id, #nome_, input[id^="nome_"]',
    produtoResultado: '#div_auto_produto_empresa_grade_id_ .typeahead-list li a, #div_auto_produto_empresa_grade_id .typeahead-list li a, #div_auto_nome_ .typeahead-list li a, [id^="div_auto_nome"] .typeahead-list li a',
    quantidade: '#quantidade_, #quantidade, #quantidade_comercial_, input[id^="quantidade_comercial"]',
    preco: '#preco_, #preco, #valor_unitario_comercial_, input[id^="valor_unitario_comercial"]',
    descricao: '#descricao_item_, #descricao, #produto_nome_, input[id^="produto_nome"]',
    btnSalvarItem: '#btn-salvar, #btn-salvar-item, button[data-action="save-item"]',
    tabelaItens: '#table-itens, #table-nfe-itens, table.table-form',
    linhasTabela: '#table-itens tbody tr, #table-nfe-itens tbody tr, table.table-form tbody tr',
    totalizador: '.col-totais, .totais-nfe, #items-summary-panel',
  },
  pagamentos: {
    painel: '#nfe-payments',
    titulo: '#nfe-payments-title h4',
    botaoNovo: '#add-nfe-payment',
    tabela: '#nfe-payments-table table',
    chargesPanel: '#panel_pagamentos, #charges-panel',
    formaPagamentoSelect: '#indicador_forma_pagamento',
    totalCobrancas: '#charges-list .charges-summary-value',
    tabelaCobrancas: '#charges-list table',
    linhasTabela: '#nfe-payments-table tbody tr',
    modal: {
      container: '.modal-content form#form_nfe_forma_pagamento',
      titulo: '.modal-content h2.orange',
      tipoPagamento: '#pagamento_tipo',
      valorPagamento: '#pagamento_valor',
      btnSalvar: '.modal-content #btn-salvar',
      btnFechar: '#btn-modal-plus-close',
      grupoCartoes: '.grupo-cartoes',
      tipoIntegracao: '#pagamento_tipo_integracao',
      bandeira: '#pagamento_bandeira_operadora',
      cnpjCredenciadora: '#pagamento_cnpj_credenciadora',
      numeroAutorizacao: '#pagamento_numero_autorizacao',
    },
  },
  ajuste: {
    painelTabs: '#tab-content-ajuste',
    form: '#form-ajuste',
    numeroAutocomplete: '#auto_numero_nfe',
    numeroHidden: '#numero_nfe',
    numeroIcone: '#auto_icon_numero_nfe',
    numeroContainer: '#div_auto_numero_nfe',
    chaveAutocomplete: '#auto_chave_acesso',
    chaveHidden: '#chave_acesso',
    chaveIcone: '#auto_icon_chave_acesso',
    chaveContainer: '#div_auto_chave_acesso',
  },
  complementar: {
    painelTabs: '#tab-content-complementar',
    form: '#form-complementar',
    numeroAutocomplete: '#auto_numero_nfe',
    numeroHidden: '#numero_nfe',
    numeroIcone: '#auto_icon_numero_nfe',
    numeroContainer: '#div_auto_numero_nfe',
    chaveAutocomplete: '#auto_chave_acesso',
    chaveHidden: '#chave_acesso',
    chaveIcone: '#auto_icon_chave_acesso',
    chaveContainer: '#div_auto_chave_acesso',
  },
  venda: {
    form: '#form-venda, form[action*="venda"]',
    campoData: 'input[name="periodo"], input[id*="periodo"], input[placeholder*="Data"]',
    campoCliente: '#auto_cliente, #auto_cliente_id, input[id*="cliente"]',
    campoClienteIcone: '#auto_icon_cliente, #auto_icon_cliente_id, [id*="auto_icon_cliente"]',
    campoPedido: '#pedido, input[name="pedido"], input[id*="pedido"]',
    botaoPesquisar: '.form_venda_botao_pesquisar #btn-pesquisar',
    tabelaResultados: '.table-hover, table tbody',
    tabelaVendas: '#table-form-body tr.table-vendas-checkbox', // Tabela de vendas com checkboxes
    primeiraLinha: 'table tbody tr:first-child',
    linhasTabela: 'table tbody tr',
    colunaCliente: 'td:nth-child(2), td:nth-child(3)', // Coluna do cliente (pode variar)
  },
  nfce: {
    form: '#form-nfce, form[action*="nfce"]',
    campoData: 'input[name="periodo"], input[id*="periodo"], input[placeholder*="Data"]',
    campoCliente: '#auto_cliente, #auto_cliente_id, input[id*="cliente"]',
    campoClienteIcone: '#auto_icon_cliente, #auto_icon_cliente_id, [id*="auto_icon_cliente"]',
    campoPedido: '#pedido, input[name="pedido"], input[id*="pedido"]',
    // ID padrão nas telas Softcom; usar sempre dentro de `nfce.form` para evitar múltiplos matches
    botaoPesquisar: '.form_venda_botao_nfce #btn-pesquisar',
    tabelaResultados: '.table-hover, table tbody',
    primeiraLinha: 'table tbody tr:first-child',
  },
  movimentacao: {
    form: '#form-movimentacao, form[action*="movimentacao"]',
    campoData: 'input[name="periodo"], input[id*="periodo"], input[placeholder*="Data"]',
    campoOperacao: 'select[name*="operacao"], select[id*="operacao"]',
    campoTipo: '#auto_tipo, #tipo, input[id*="tipo"], input[name*="tipo"]',
    campoCliente: '#auto_cliente, #auto_cliente_id, input[id*="cliente"]',
    campoClienteIcone: '#auto_icon_cliente, #auto_icon_cliente_id, [id*="auto_icon_cliente"]',
    campoPedido: '#pedido, input[name="pedido"], input[id*="pedido"]',
    botaoPesquisar: '.form_movimentacao_botao_pesquisar #btn-pesquisar',
    tabelaResultados: 'table tbody, .table-hover tbody',
    primeiraLinha: 'table tbody tr:first-child',
  },
  devolucao: {
    compra: {
      form: '#form-compra, form[action*="compra"]',
      campoData: 'input[name="periodo"], input[id*="periodo"], input[placeholder*="Data"]',
      campoFornecedor: '#auto_fornecedor, #auto_fornecedor_id, input[id*="fornecedor"]',
      campoFornecedorIcone: '#auto_icon_fornecedor, #auto_icon_fornecedor_id, [id*="auto_icon_fornecedor"]',
      campoCnpj: '#auto_cnpj, #cnpj, input[id*="cnpj"]',
      campoCnpjIcone: '#auto_icon_cnpj, [id*="auto_icon_cnpj"]',
      campoNotaFiscal: '#auto_nota_fiscal, #nota_fiscal, input[id*="nota_fiscal"]',
      campoNotaFiscalIcone: '#auto_icon_nota_fiscal, [id*="auto_icon_nota_fiscal"]',
      campoChaveAcesso: '#auto_chave_acesso, #chave_acesso, input[id*="chave_acesso"]',
      campoChaveAcessoIcone: '#auto_icon_chave_acesso, [id*="auto_icon_chave_acesso"]',
      botaoPesquisar: '.form_compra_botao_pesquisar #btn-pesquisar',
      tabelaResultados: 'table tbody, .table-hover tbody',
      tabelaCompras: 'table tbody tr.table-compras-checkbox',
      botaoAcoesLinha: 'button.dropdown-toggle, button[type="button"][data-toggle="dropdown"]',
      linkGerarDevolucao: 'a:contains("Gerar nota de devolução"), #btn-nota-devolucao',
      primeiraLinha: 'table tbody tr:first-child',
      // Modal de seleção de itens
      modalSelecaoItens: '[role="dialog"], .modal, [class*="modal"]',
      modalTitulo: 'h2:contains("Dados da nota fiscal de compra")',
      modalTabelaItens: '[role="dialog"] table, .modal table',
      modalCheckboxItem: '[role="dialog"] table tbody tr input[type="checkbox"], .modal table tbody tr input[type="checkbox"]',
      modalCampoQuantidade: '[role="dialog"] table tbody tr input[type="text"], .modal table tbody tr input[type="text"]',
      modalTotalItens: 'h5:contains("Total de Itens")',
      modalTotalVolumes: 'h5:contains("Total de Volumes")',
      modalItensSelecionados: 'h5:contains("Itens Selecionados")',
      modalVolumeSelecionado: 'h5:contains("Volume Selecionado")',
      modalBotaoCancelar: 'button:contains("Cancelar")',
      modalBotaoGerar: 'button:contains("Gerar Nota de Devolução")',
    },
    movimentacao: {
      form: '#form-movimentacao-devolucao, form[action*="movimentacao"]',
      campoData: 'input[name="periodo"], input[id*="periodo"], input[placeholder*="Data"]',
      campoFornecedor: '#auto_fornecedor, #auto_fornecedor_id, input[id*="fornecedor"]',
      campoFornecedorIcone: '#auto_icon_fornecedor, #auto_icon_fornecedor_id, [id*="auto_icon_fornecedor"]',
      campoCnpj: '#auto_cnpj, #cnpj, input[id*="cnpj"]',
      campoCnpjIcone: '#auto_icon_cnpj, [id*="auto_icon_cnpj"]',
      campoNotaFiscal: '#auto_nota_fiscal, #nota_fiscal, input[id*="nota_fiscal"]',
      campoNotaFiscalIcone: '#auto_icon_nota_fiscal, [id*="auto_icon_nota_fiscal"]',
      campoChaveAcesso: '#auto_chave_acesso, #chave_acesso, input[id*="chave_acesso"]',
      campoChaveAcessoIcone: '#auto_icon_chave_acesso, [id*="auto_icon_chave_acesso"]',
      botaoPesquisar: '.form_movimentacao_botao_pesquisar #btn-pesquisar',
      tabelaResultados: '.table-hover, table tbody',
      primeiraLinha: 'table tbody tr:first-child',
    },
    notaFiscalSaida: {
      form: '#form-nota-fiscal-saida, form[action*="nota_fiscal_saida"]',
      campoData: 'input[name="periodo"], input[id*="periodo"], input[placeholder*="Data"]',
      campoCliente: '#auto_cliente, #auto_cliente_id, input[id*="cliente"]',
      campoClienteIcone: '#auto_icon_cliente, #auto_icon_cliente_id, [id*="auto_icon_cliente"]',
      campoCnpj: '#auto_cnpj, #cnpj, input[id*="cnpj"]',
      campoCnpjIcone: '#auto_icon_cnpj, [id*="auto_icon_cnpj"]',
      campoNotaFiscal: '#auto_nota_fiscal, #nota_fiscal, input[id*="nota_fiscal"]',
      campoNotaFiscalIcone: '#auto_icon_nota_fiscal, [id*="auto_icon_nota_fiscal"]',
      campoChaveAcesso: '#auto_chave_acesso, #chave_acesso, input[id*="chave_acesso"]',
      campoChaveAcessoIcone: '#auto_icon_chave_acesso, [id*="auto_icon_chave_acesso"]',
      botaoPesquisar: '.form_nota_fiscal_botao_pesquisar #btn-pesquisar',
      tabelaResultados: '.table-hover, table tbody',
      primeiraLinha: 'table tbody tr:first-child',
    },
    trocas: {
      form: '#form-trocas, form[action*="trocas"]',
      campoData: 'input[name="periodo"], input[id*="periodo"], input[placeholder*="Data"]',
      campoCliente: '#auto_cliente, #auto_cliente_id, input[id*="cliente"]',
      campoClienteIcone: '#auto_icon_cliente, #auto_icon_cliente_id, [id*="auto_icon_cliente"]',
      botaoPesquisar: '.form_trocas_botao_pesquisar #btn-pesquisar',
      tabelaResultados: '.table-hover, table tbody',
      primeiraLinha: 'table tbody tr:first-child',
    },
  },
};

export default CadastroNfeLocators;
