const CadastroClienteLocators = {
  containerTabs: '#tabs-cliente',
  abaDadosCadastrais: 'a[href="#dados-cadastrais"]',
  abaUltimasCompras: '#tab-ultimas-compras',
  abaCreditoCliente: '#tab-cliente-credito',
  abasExtras: '#tabs-cliente .nav-tabs li a',
  btnVoltar: '#btn-voltar',
  btnNovo: '#btn-novo',
  formPessoaFisica: '#form-pessoa-fisica',
  selectPessoa: '#pessoa',
  inputCpfCnpj: '#cpf_cnpj',
  inputInscricaoEstadual: '#inscricao_estadual',
  inputRg: '#rg',
  selectContribuinte: '#contribuinte_icms',
  inputNome: '#nome',
  inputCep: '#cep',
  btnBuscarCep: '#busca-cep_cep',
  inputEndereco: '#endereco',
  inputNumero: '#numero',
  inputComplemento: '#complemento',
  inputAutoBairro: '#auto_bairro',
  hiddenBairro: '#bairro',
  inputAutoCidade: '#auto_cidade_id',
  hiddenCidade: '#cidade_id',
  inputDataNascimento: '#data_nascimento',
  inputAutoArea: '#auto_area_id',
  inputAutoFuncionario: '#auto_funcionario_id',
  selectIndicadorFinalidade: '#indicador_finalidade',
  inputAutoTipoCliente: '#auto_tipo_cliente_id',
  hiddenTipoCliente: '#tipo_cliente_id',
  switchBloqueadoCheckbox: '#switcher_bloqueado',
  switchBloqueadoToggle: '#switcher_bloqueado + .switchery',
  switchDesativadoCheckbox: '#switcher_desativado',
  switchDesativadoToggle: '#switcher_desativado + .switchery',
  textareaObservacao: '#observacao',
  selectTagClassificacao: '#tag_classificacao_id',
  inputAutoTagClassificacao: '#auto_button_add_tag',
  btnSalvar: '#btn-salvar'
};

export default CadastroClienteLocators;
