const CadastroClienteLocators = {
  containerTabs: '#tabs-cliente',
  abaDadosCadastrais: 'a[href="#dados-cadastrais"]',
  abaUltimasCompras: '#tab-ultimas-compras',
  abaCreditoCliente: '#tab-cliente-credito',
  abasExtras: '#tabs-cliente .nav-tabs li a',
  abaOutrosEnderecos: '#tabs-cliente .nav-tabs li a[data-action*="cliente-endereco"]',
  abaContatoNotificacoes: '#tab-contato-notificacoes',
  painelOutrosEnderecos: '#outros-endere-os',
  painelContatoNotificacoes: '#contato-notifica-es',
  btnContato: '#btn-contato',
  modalContato: '#modal-contato',
  modalContatoTitulo: '#modal-contato #title-simplemodal',
  modalContatoBody: '#modal-body-contato',
  tabelaContatos: '#contato-notifica-es .table-contato',
  tabelaHistoricoNotificacoes: '#contato-notifica-es .table-historico-notificacoes',
  mensagemSemContatos: '#contato-notifica-es .table-contato td[colspan]',
  mensagemSemHistorico: '#contato-notifica-es .table-historico-notificacoes td[colspan]',
  tabelaOutrosEnderecos: '#outros-endere-os table',
  linhasOutrosEnderecos: '#outros-endere-os tbody tr',
  mensagemSemEnderecos: '#outros-endere-os td[colspan]',
  btnNovoEndereco: '#btn-endereco',
  modalEndereco: '#modal-endereco',
  modalEnderecoTitulo: '#modal-endereco #title-simplemodal',
  modalEnderecoBody: '#modal-body-endereco',
  modalEnderecoFormulario: '#form-modal-endereco',
  modalEnderecoSelectTipo: '#form-modal-endereco #tipo',
  modalEnderecoInputCep: '#form-modal-endereco #cep',
  modalEnderecoBtnBuscarCep: '#form-modal-endereco #busca-cep_cep',
  modalEnderecoInputNumero: '#form-modal-endereco #numero',
  modalEnderecoInputEndereco: '#form-modal-endereco #endereco',
  modalEnderecoInputCidade: '#form-modal-endereco #auto_endereco_cidade_id',
  modalEnderecoHiddenCidade: '#form-modal-endereco #endereco_cidade_id',
  modalEnderecoListaCidades: '#div_auto_endereco_cidade_id .typeahead-list li a',
  modalEnderecoInputBairro: '#form-modal-endereco #auto_bairro',
  modalEnderecoHiddenBairro: '#form-modal-endereco #bairro',
  modalEnderecoListaBairros: '#div_auto_bairro .typeahead-list li a',
  modalEnderecoInputComplemento: '#form-modal-endereco #complemento',
  modalEnderecoBtnSalvar: '#form-modal-endereco #btn-salvar',
  modalContato: '#modal-contato',
  modalContatoTitulo: '#modal-contato #title-simplemodal',
  modalContatoBody: '#modal-body-contato',
  modalContatoFormulario: '#form-modal-contato',
  modalContatoSelectTipo: '#form-modal-contato #tipo',
  modalContatoInputNome: '#form-modal-contato #nome',
  modalContatoInputDDD: '#form-modal-contato #ddd',
  modalContatoInputTelefone: '#form-modal-contato #telefone',
  modalContatoInputEmail: '#form-modal-contato #email',
  modalContatoBtnSalvar: '#form-modal-contato #btn-salvar',
  btnVoltar: '#btn-voltar',
  btnNovo: '#btn-novo',
  formPessoaFisica: '#form-pessoa-fisica',
  formPessoaJuridica: '#form-pessoa-juridica',
  selectPessoa: '#pessoa',
  inputCpfCnpj: '#cpf_cnpj',
  inputInscricaoEstadual: '#inscricao_estadual',
  inputInscricaoMunicipal: '#inscricao_municipal',
  inputRg: '#rg',
  selectContribuinte: '#contribuinte_icms',
  inputNome: '#nome',
  inputRazaoSocial: '#razao_social',
  inputCep: '#cep',
  btnBuscarCep: '#busca-cep_cep',
  inputEndereco: '#endereco',
  inputNumero: '#numero',
  inputComplemento: '#complemento',
  inputAutoBairro: '#auto_bairro',
  inputAutoBairroIcone: '#auto_icon_bairro',
  hiddenBairro: '#bairro',
  listaResultadosBairro: '#div_auto_bairro .typeahead-list li a',
  inputAutoCidade: '#auto_cidade_id',
  inputAutoCidadeIcone: '#auto_icon_cidade_id',
  hiddenCidade: '#cidade_id',
  listaResultadosCidade: '#div_auto_cidade_id .typeahead-list li a',
  inputDataNascimento: '#data_nascimento',
  inputAutoArea: '#auto_area_id',
  inputAutoFuncionario: '#auto_funcionario_id',
  selectIndicadorFinalidade: '#indicador_finalidade',
  inputAutoTipoCliente: '#auto_tipo_cliente_id',
  hiddenTipoCliente: '#tipo_cliente_id',
  switchBloqueadoCheckbox: '#switcher_bloqueado',
  switchBloqueadoToggle: '#switcher_bloqueado + .switchery',
  switchDesativadoCheckbox: '#switcher_desativado',
  switchDesativadoToggle: '#switcher_desativado + .switchery',
  textareaObservacao: '#observacao',
  selectTagClassificacao: '#tag_classificacao_id',
  inputAutoTagClassificacao: '#auto_button_add_tag',
  btnSalvar: '#btn-salvar'
};

export default CadastroClienteLocators;
