const ProdutoLocators = {
  abaDadosCadastrais: 'a[href="#dados-cadastrais"]',
  abaDetalhesFiscais: "#tabs-detalhes-fiscais",
  abaProdutoEmpresa: "#tabs-produto-empresa",
  abasComposicao: "#tabs-produto-composicao",
  abasFotos: "#tabs-imagens",
  abaGrade: "#tabs-produto-grade",
  abaCombo: "#tabs-produto-combo",
  gradeTabContent: "#grade",
  comboTabContent: "#combo",
  gradeBotaoMontar: "#btn-grade",
  comboBotaoAdicionarItem: "#btn-adicionar-item",
  gradeTabelaSemResultados: "#grade #table-form-body td",
  comboTabelaMensagens: "#table-produto-combo tbody td",
  comboTabelaLinhas: "#table-produto-combo tbody tr",
  comboModalGrupoExpansores: "#content-plus .accordion-button",
  comboModalContainer: "#content-plus",
  comboModal: "#content-plus .modal-dialog",
  comboModalDescricao: "#content-plus #descricao",
  comboModalOrdem: "#content-plus #ordem",
  comboModalQuantidadeMinima: "#content-plus #quantidade_minima",
  comboModalQuantidadeMaxima: "#content-plus #quantidade_maxima",
  comboModalProdutos: "#content-plus .produtos-item",
  comboModalProdutoCheckbox: ".checkbox-item",
  comboModalProdutoPreco: "input#preco_venda:not([type='hidden'])",
  comboModalSalvarButton: "#btn-salvar-combo-item",
  comboModalVoltarButton: "#btn-voltar-combo-item",
  gradeModal: "#modal-grade",
  gradeModalTitulo: "#modal-grade #title-simplemodal",
  gradeModalTipoSelect: "#modal-grade select#tipo",
  gradeModalSalvarButton: "#modal-grade #adicionar-item",
  gradeModalCloseButton: "#modal-grade .close",
  gradeModalAtributoUmSelect: "#atributo-simplificada-1",
  gradeModalAtributoDoisSelect: "#atributo-simplificada-2",
  gradeModalItemUmIcone: "#auto_icon_item1",
  gradeModalItemDoisIcone: "#auto_icon_item2",
  gradeModalItemUmOpcoes: "#div_auto_item1 .typeahead-list li a",
  gradeModalItemDoisOpcoes: "#div_auto_item2 .typeahead-list li a",
  gradeModalLinhaNome: "#linha-atributo-1 .linha-nome",
  gradeModalItemCodigoBarras: (index) =>
    `#linha-atributo-1 .linha-nome:nth-child(${index + 1}) .row-codigo-barras`,
  gradeTabelaComItens: "#grade .table-produto-grade tbody tr",
  formProduto: "#form-produto",
  nomeInput: "#nome",
  referenciaInput: "#referencia",
  codigoBarrasInput: "#codigo_barras",
  grupoDropdownIcon: "#auto_icon_grupo_id",
  grupoOpcaoPadrao: "#div_auto_grupo_id .typeahead-list li:first-child a",
  unidadeDropdownIcon: "#auto_icon_unidade_medida_id",
  unidadeOpcaoPrimeira:
    "#div_auto_unidade_medida_id .typeahead-list li:first-child a",
  precoCompraInput: "#preco_compra",
  margemLucroInput: "#margem_lucro",
  precoVendaInput: "#preco_venda",
  percentualComissaoInput: "#percentual_comissao_produto",
  estoqueInicialInput: "#estoque_inicial",
  pesoInput: "#peso",
  alturaInput: "#altura",
  larguraInput: "#largura",
  comprimentoInput: "#comprimento",
  observacaoTextarea: "#observacao",
  informacaoAdicionalTextarea: "#informacao_adicional",
  btnSalvar: "#btn-salvar",
  venderHidden: "#vender",
  venderCheckbox: "#switcher_vender",
  venderToggle: "#switcher_vender + .switchery",
  alertaDadosFiscais: ".swal2-popup, .sweet-alert",
  alertaDadosFiscaisTitulo: "#swal2-title, .sweet-alert h2",
  alertaDadosFiscaisMensagem: "#swal2-html-container, .sweet-alert p",
  alertaDadosFiscaisConfirmar: "button.swal2-confirm, .sweet-alert button.confirm",
  alertaDadosFiscaisCancelar: "button.swal2-cancel, .sweet-alert button.cancel",
  detalhesFiscaisTitulo: ".ibox-title h5",
  formImpostos: "#form-impostos",
  autoVinculoFiscalId: "#auto_icon_vinculo_fiscal_id",
  btnExcluir: "#btn-excluir",
  alertaExcluirProduto: ".modal-confirm-destroy",
  alertaExcluirProdutoTitulo: ".modal-confirm-destroy h2",
  alertaExcluirProdutoMensagem: ".modal-confirm-destroy p",
  alertaExcluirProdutoConfirmar: ".modal-confirm-destroy button.confirm",
  alertaExcluirProdutoCancelar: ".modal-confirm-destroy button.cancel",
  switcherHabilitarGradeInput: "#switcher_habilitar_grade",
  switcherHabilitarGradeToggle: "#switcher_habilitar_grade + .switchery",
  habilitarGradeHidden: "#habilitar_grade",
  switcherHabilitarComboToggle: "#switcher_habilitar_acompanhamento + .switchery",
  switcherHabilitarComboInput: "#switcher_habilitar_acompanhamento",
  habilitarComboHidden: "#habilitar_acompanhamento",
  comboResumoQuantidadeLabel: ".totalizador-div strong",
};

export default ProdutoLocators;
